application: lyth-resume
version: 2
runtime: go
api_version: go1

handlers:
- url: /sitemap\.xml
  static_files: sitemap.xml
  upload: sitemap\.xml

- url: /(index\.html)?
  static_files: webapp/index.html
  upload: webapp/index\.html

- url: /favicon\.ico
  static_files: webapp/favicon.ico
  upload: webapp/favicon\.ico

- url: /css
  static_dir: webapp/css

- url: /img
  static_dir: webapp/img

- url: /js
  static_dir: webapp/js

- url: /lib
  static_dir: webapp/lib

- url: /partials
  static_dir: webapp/partials

- url: /api*
  script: _go_app

